spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: メールアドレス # FIXME
    password: アプリパスワード # FIXME
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    check-template-location: false
